get_tangent_slopes <- function(R, x_c, y_c, x_p, y_p) {
  m1 <- (-R*sqrt(-R**2 + x_c**2 - 2*x_c*x_p + x_p**2 + y_c**2 - 2*y_c*y_p + y_p**2) - x_c*y_c + x_c*y_p + x_p*y_c - x_p*y_p)/(R**2 - x_c**2 + 2*x_c*x_p - x_p**2)
  m2 <- (R*sqrt(-R**2 + x_c**2 - 2*x_c*x_p + x_p**2 + y_c**2 - 2*y_c*y_p + y_p**2) - x_c*y_c + x_c*y_p + x_p*y_c - x_p*y_p)/(R**2 - x_c**2 + 2*x_c*x_p - x_p**2)
  c(m1, m2)
} 
 get_tangent_points <- function(R, x_c, y_c, x_p, y_p) {
  x1 <- (x_c*(R**2 - x_c**2 + 2*x_c*x_p - x_p**2)**2 - y_c*(R**2 - x_c**2 + 2*x_c*x_p - x_p**2)*(R*sqrt(-R**2 + x_c**2 - 2*x_c*x_p + x_p**2 + y_c**2 - 2*y_c*y_p + y_p**2) + x_c*y_c - x_c*y_p - x_p*y_c + x_p*y_p) - (x_p*(-R*sqrt(-R**2 + x_c**2 - 2*x_c*x_p + x_p**2 + y_c**2 - 2*y_c*y_p + y_p**2) - x_c*y_c + x_c*y_p + x_p*y_c - x_p*y_p) - y_p*(R**2 - x_c**2 + 2*x_c*x_p - x_p**2))*(R*sqrt(-R**2 + x_c**2 - 2*x_c*x_p + x_p**2 + y_c**2 - 2*y_c*y_p + y_p**2) + x_c*y_c - x_c*y_p - x_p*y_c + x_p*y_p))/((R**2 - x_c**2 + 2*x_c*x_p - x_p**2)**2 + (R*sqrt(-R**2 + x_c**2 - 2*x_c*x_p + x_p**2 + y_c**2 - 2*y_c*y_p + y_p**2) + x_c*y_c - x_c*y_p - x_p*y_c + x_p*y_p)**2)
  x2 <- (x_c*(R**2 - x_c**2 + 2*x_c*x_p - x_p**2)**2 + y_c*(R**2 - x_c**2 + 2*x_c*x_p - x_p**2)*(R*sqrt(-R**2 + x_c**2 - 2*x_c*x_p + x_p**2 + y_c**2 - 2*y_c*y_p + y_p**2) - x_c*y_c + x_c*y_p + x_p*y_c - x_p*y_p) + (x_p*(R*sqrt(-R**2 + x_c**2 - 2*x_c*x_p + x_p**2 + y_c**2 - 2*y_c*y_p + y_p**2) - x_c*y_c + x_c*y_p + x_p*y_c - x_p*y_p) - y_p*(R**2 - x_c**2 + 2*x_c*x_p - x_p**2))*(R*sqrt(-R**2 + x_c**2 - 2*x_c*x_p + x_p**2 + y_c**2 - 2*y_c*y_p + y_p**2) - x_c*y_c + x_c*y_p + x_p*y_c - x_p*y_p))/((R**2 - x_c**2 + 2*x_c*x_p - x_p**2)**2 + (R*sqrt(-R**2 + x_c**2 - 2*x_c*x_p + x_p**2 + y_c**2 - 2*y_c*y_p + y_p**2) - x_c*y_c + x_c*y_p + x_p*y_c - x_p*y_p)**2)
  y1 <- (x_p*((R**2 - x_c**2 + 2*x_c*x_p - x_p**2)**2 + (R*sqrt(-R**2 + x_c**2 - 2*x_c*x_p + x_p**2 + y_c**2 - 2*y_c*y_p + y_p**2) + x_c*y_c - x_c*y_p - x_p*y_c + x_p*y_p)**2)*(R*sqrt(-R**2 + x_c**2 - 2*x_c*x_p + x_p**2 + y_c**2 - 2*y_c*y_p + y_p**2) + x_c*y_c - x_c*y_p - x_p*y_c + x_p*y_p) + y_p*((R**2 - x_c**2 + 2*x_c*x_p - x_p**2)**2 + (R*sqrt(-R**2 + x_c**2 - 2*x_c*x_p + x_p**2 + y_c**2 - 2*y_c*y_p + y_p**2) + x_c*y_c - x_c*y_p - x_p*y_c + x_p*y_p)**2)*(R**2 - x_c**2 + 2*x_c*x_p - x_p**2) - (x_c*(R**2 - x_c**2 + 2*x_c*x_p - x_p**2)**2 - y_c*(R**2 - x_c**2 + 2*x_c*x_p - x_p**2)*(R*sqrt(-R**2 + x_c**2 - 2*x_c*x_p + x_p**2 + y_c**2 - 2*y_c*y_p + y_p**2) + x_c*y_c - x_c*y_p - x_p*y_c + x_p*y_p) + (x_p*(R*sqrt(-R**2 + x_c**2 - 2*x_c*x_p + x_p**2 + y_c**2 - 2*y_c*y_p + y_p**2) + x_c*y_c - x_c*y_p - x_p*y_c + x_p*y_p) + y_p*(R**2 - x_c**2 + 2*x_c*x_p - x_p**2))*(R*sqrt(-R**2 + x_c**2 - 2*x_c*x_p + x_p**2 + y_c**2 - 2*y_c*y_p + y_p**2) + x_c*y_c - x_c*y_p - x_p*y_c + x_p*y_p))*(R*sqrt(-R**2 + x_c**2 - 2*x_c*x_p + x_p**2 + y_c**2 - 2*y_c*y_p + y_p**2) + x_c*y_c - x_c*y_p - x_p*y_c + x_p*y_p))/(((R**2 - x_c**2 + 2*x_c*x_p - x_p**2)**2 + (R*sqrt(-R**2 + x_c**2 - 2*x_c*x_p + x_p**2 + y_c**2 - 2*y_c*y_p + y_p**2) + x_c*y_c - x_c*y_p - x_p*y_c + x_p*y_p)**2)*(R**2 - x_c**2 + 2*x_c*x_p - x_p**2))
  y2 <- (-x_p*((R**2 - x_c**2 + 2*x_c*x_p - x_p**2)**2 + (R*sqrt(-R**2 + x_c**2 - 2*x_c*x_p + x_p**2 + y_c**2 - 2*y_c*y_p + y_p**2) - x_c*y_c + x_c*y_p + x_p*y_c - x_p*y_p)**2)*(R*sqrt(-R**2 + x_c**2 - 2*x_c*x_p + x_p**2 + y_c**2 - 2*y_c*y_p + y_p**2) - x_c*y_c + x_c*y_p + x_p*y_c - x_p*y_p) + y_p*((R**2 - x_c**2 + 2*x_c*x_p - x_p**2)**2 + (R*sqrt(-R**2 + x_c**2 - 2*x_c*x_p + x_p**2 + y_c**2 - 2*y_c*y_p + y_p**2) - x_c*y_c + x_c*y_p + x_p*y_c - x_p*y_p)**2)*(R**2 - x_c**2 + 2*x_c*x_p - x_p**2) + (x_c*(R**2 - x_c**2 + 2*x_c*x_p - x_p**2)**2 + y_c*(R**2 - x_c**2 + 2*x_c*x_p - x_p**2)*(R*sqrt(-R**2 + x_c**2 - 2*x_c*x_p + x_p**2 + y_c**2 - 2*y_c*y_p + y_p**2) - x_c*y_c + x_c*y_p + x_p*y_c - x_p*y_p) + (x_p*(R*sqrt(-R**2 + x_c**2 - 2*x_c*x_p + x_p**2 + y_c**2 - 2*y_c*y_p + y_p**2) - x_c*y_c + x_c*y_p + x_p*y_c - x_p*y_p) - y_p*(R**2 - x_c**2 + 2*x_c*x_p - x_p**2))*(R*sqrt(-R**2 + x_c**2 - 2*x_c*x_p + x_p**2 + y_c**2 - 2*y_c*y_p + y_p**2) - x_c*y_c + x_c*y_p + x_p*y_c - x_p*y_p))*(R*sqrt(-R**2 + x_c**2 - 2*x_c*x_p + x_p**2 + y_c**2 - 2*y_c*y_p + y_p**2) - x_c*y_c + x_c*y_p + x_p*y_c - x_p*y_p))/(((R**2 - x_c**2 + 2*x_c*x_p - x_p**2)**2 + (R*sqrt(-R**2 + x_c**2 - 2*x_c*x_p + x_p**2 + y_c**2 - 2*y_c*y_p + y_p**2) - x_c*y_c + x_c*y_p + x_p*y_c - x_p*y_p)**2)*(R**2 - x_c**2 + 2*x_c*x_p - x_p**2))
  data.frame(
    x = c(x1, x2),
    y = c(y1, y2)
  )
}